parameters:
    env(JWT_PRIVATE_KEY_PATH): config/jwt/private.pem
    env(JWT_PUBLIC_KEY_PATH): config/jwt/public.pem

lexik_jwt_authentication:
    private_key_path: '%kernel.project_dir%/%env(JWT_PRIVATE_KEY_PATH)%'
    public_key_path: '%kernel.project_dir%/%env(JWT_PUBLIC_KEY_PATH)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600

    encoder:
        service: lexik_jwt_authentication.encoder.default
        crypto_engine: openssl
        signature_algorithm: RS256

    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        query_parameter:
            enabled: true
            name: token
        cookie:
            enabled: false
            name: TOKEN
