services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    'App\Bundle\SwooleBundle\Component\AtomicCounter':
        factory: ['App\Bundle\SwooleBundle\Component\AtomicCounter', fromZero]

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\RequestFactoryInterface':
        class: App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\RequestFactory

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface':
        class: App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\ResponseProcessor

    'App\Bundle\SwooleBundle\Server\RequestHandlerInterface':
        class: App\Bundle\SwooleBundle\Bridge\Symfony\HttpKernel\HttpKernelRequestHandler

    'App\Bundle\SwooleBundle\Server\LimitedRequestHandler':

    'App\Bundle\SwooleBundle\Server\HttpServerConfiguration':

    'app.swoole.server.http_server.server_instance':
        class: Swoole\Http\Server
        lazy: true

    'App\Bundle\SwooleBundle\Server\HttpServer':
        arguments: ['@app.swoole.server.http_server.server_instance']

    'App\Bundle\SwooleBundle\Command\ServerRunCommand':
        tags: ['console.command']

    'App\Bundle\SwooleBundle\Command\ServerProfileCommand':
        tags: ['console.command']
        arguments:
            $driver: '@App\Bundle\SwooleBundle\Server\LimitedRequestHandler'
