services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    'App\Bundle\SwooleBundle\Component\AtomicCounter':
        factory: ['App\Bundle\SwooleBundle\Component\AtomicCounter', fromZero]

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\SetRequestRuntimeConfiguration':

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\RequestFactoryInterface':
        class: App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\RequestFactory

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface':
        class: App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\ResponseProcessor

    'App\Bundle\SwooleBundle\Server\RequestHandler\RequestHandlerInterface':
        class: App\Bundle\SwooleBundle\Bridge\Symfony\HttpKernel\HttpKernelRequestHandler

    'App\Bundle\SwooleBundle\Server\RequestHandler\LimitedRequestHandler':

    'App\Bundle\SwooleBundle\Server\Runtime\BootManager':
        autoconfigure: false

    'App\Bundle\SwooleBundle\Server\HttpServer':

    'App\Bundle\SwooleBundle\Server\HttpServerConfiguration':

    'App\Bundle\SwooleBundle\Server\Configurator\ConfiguratorInterface':
        class: App\Bundle\SwooleBundle\Server\Configurator\WithHttpServerConfiguration

    'App\Bundle\SwooleBundle\Server\Configurator\WithLimitedRequestHandler':

    'App\Bundle\SwooleBundle\Server\Configurator\WithRequestHandler':

    'app.swoole.server.http_server.normal_factory':
        class: App\Bundle\SwooleBundle\Server\HttpServerFactory
        arguments:
            $configurator: '@App\Bundle\SwooleBundle\Server\Configurator\WithRequestHandler'

    'App\Bundle\SwooleBundle\Command\ServerRunCommand':
        tags: ['console.command']
        arguments:
            $serverFactory: '@app.swoole.server.http_server.normal_factory'

    'app.swoole.server.http_server.limited_factory':
        class: App\Bundle\SwooleBundle\Server\HttpServerFactory
        arguments:
            $configurator: '@App\Bundle\SwooleBundle\Server\Configurator\WithLimitedRequestHandler'

    'App\Bundle\SwooleBundle\Command\ServerProfileCommand':
        tags: ['console.command']
        arguments:
            $serverFactory: '@app.swoole.server.http_server.limited_factory'
