services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    'App\Bundle\SwooleBundle\Server\AtomicCounter':
        factory: [App\Bundle\SwooleBundle\Server\AtomicCounter, fromZero]

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\RequestFactoryInterface':
        class: App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\RequestFactory

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\CloudFrontRequestFactory':
        decorates: App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\RequestFactoryInterface
        decoration_priority: -10
        arguments: ['@App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\CloudFrontRequestFactory.inner']
        autoconfigure: false

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface':
        class: App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\ResponseProcessor

    'App\Bundle\SwooleBundle\Driver\HttpDriverInterface':
        class: App\Bundle\SwooleBundle\Bridge\Symfony\HttpKernel\HttpKernelHttpDriver

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\TrustAllProxiesHttpDriver':
        decorates: App\Bundle\SwooleBundle\Driver\HttpDriverInterface
        decoration_priority: -10
        arguments: ['@App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\TrustAllProxiesHttpDriver.inner']
        autoconfigure: false

    'App\Bundle\SwooleBundle\Bridge\Doctrine\ORM\EntityManagerHttpDriver':
        decorates: App\Bundle\SwooleBundle\Driver\HttpDriverInterface
        decoration_priority: -20
        arguments: ['@App\Bundle\SwooleBundle\Bridge\Doctrine\ORM\EntityManagerHttpDriver.inner']
        autoconfigure: false

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpKernel\DebugHttpKernelHttpDriver':
        decorates: App\Bundle\SwooleBundle\Driver\HttpDriverInterface
        decoration_priority: -50
        arguments: ['@App\Bundle\SwooleBundle\Bridge\Symfony\HttpKernel\DebugHttpKernelHttpDriver.inner']
        autoconfigure: false

    'App\Bundle\SwooleBundle\Driver\LimitedHttpDriver':

    'Swoole\Http\Server':

    'App\Bundle\SwooleBundle\Command\ServerRunCommand':
        tags: ['console.command']
    'App\Bundle\SwooleBundle\Command\ServerProfileCommand':
        tags: ['console.command']
        arguments:
          $driver: '@App\Bundle\SwooleBundle\Driver\LimitedHttpDriver'
