services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    'App\Bundle\SwooleBundle\Component\AtomicCounter':
        factory: ['App\Bundle\SwooleBundle\Component\AtomicCounter', fromZero]

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\RequestFactoryInterface':
        class: App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\RequestFactory

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\CloudFrontRequestFactory':
        decorates: App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\RequestFactoryInterface
        decoration_priority: -10
        arguments: ['@App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\CloudFrontRequestFactory.inner']
        autoconfigure: false

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface':
        class: App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\ResponseProcessor

    'App\Bundle\SwooleBundle\Server\HttpServerDriverInterface':
        class: App\Bundle\SwooleBundle\Bridge\Symfony\HttpKernel\HttpKernelHttpServerDriver

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\TrustAllProxiesHttpServerDriver':
        decorates: App\Bundle\SwooleBundle\Server\HttpServerDriverInterface
        decoration_priority: -10
        arguments: ['@App\Bundle\SwooleBundle\Bridge\Symfony\HttpFoundation\TrustAllProxiesHttpServerDriver.inner']
        autoconfigure: false

    'App\Bundle\SwooleBundle\Bridge\Doctrine\ORM\EntityManagerHttpServerDriver':
        decorates: App\Bundle\SwooleBundle\Server\HttpServerDriverInterface
        decoration_priority: -20
        arguments: ['@App\Bundle\SwooleBundle\Bridge\Doctrine\ORM\EntityManagerHttpServerDriver.inner']
        autoconfigure: false

    'App\Bundle\SwooleBundle\Bridge\Symfony\HttpKernel\DebugHttpKernelHttpServerDriver':
        decorates: App\Bundle\SwooleBundle\Server\HttpServerDriverInterface
        decoration_priority: -50
        arguments: ['@App\Bundle\SwooleBundle\Bridge\Symfony\HttpKernel\DebugHttpKernelHttpServerDriver.inner']
        autoconfigure: false

    'App\Bundle\SwooleBundle\Server\LimitedHttpServerDriver':

    'App\Bundle\SwooleBundle\Server\HttpServerConfiguration':

    'app.swoole.server.http_server.server_instance':
        class: Swoole\Http\Server
        lazy: true

    'App\Bundle\SwooleBundle\Server\HttpServer':
        arguments: ['@app.swoole.server.http_server.server_instance']

    'App\Bundle\SwooleBundle\Command\ServerRunCommand':
        tags: ['console.command']

    'App\Bundle\SwooleBundle\Command\ServerProfileCommand':
        tags: ['console.command']
        arguments:
          $driver: '@App\Bundle\SwooleBundle\Server\LimitedHttpServerDriver'
