parameters:
    env(HOST): localhost
    env(PORT): 9501

swoole:
    http_server:
        port: '%env(int:PORT)%'
        host: '%env(HOST)%'
        static:
            strategy: 'advanced'
        services:
            debug: true
            trust_all_proxies: true
            entity_manager_handler: true
        settings:
            worker_count: 4
            reactor_count: 2
