api_platform:
    http_cache:
        invalidation:
            # To enable the tags-based cache invalidation system.
            enabled: true

        # Default value for the response shared (proxy) max age.
        shared_max_age: 3600
