parameters:
    env(HOST): localhost
    env(PORT): 9501

swoole:
    http_server:
        port: '%env(int:PORT)%'
        host: '%env(HOST)%'
        services:
            trust_all_proxies: true
            entity_manager_handler: true
            cloudfront_proto_header_handler: true
