imports:
    - { resource: '../prod/nelmio_cors.php' }
    - { resource: '../prod/doctrine.yaml' }
    - { resource: '../prod/framework.yaml' }
    - { resource: '../prod/monolog.php' }
    - { resource: '../prod/swoole.yaml' }